import matplotlib
# Force Matplotlib to use the non-interactive backend for script execution
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from flyvis import NetworkView
from flyvis.analysis.moving_bar_responses import plot_angular_tuning

# 1. Load the network
print("Loading network...")
network = NetworkView("flow/0000/000")

# 2. Run the simulation 
print("Running moving edge simulation...")
stims_and_resps = network.moving_edge_responses()

# 3. Generate the plot directly (do not create subplots manually)
print("Generating plot...")
plot_angular_tuning(stims_and_resps, "T4a", 1.0)

# 4. Save the active figure generated by the function
plt.savefig("tools/angular_tuning_output.png", bbox_inches='tight', facecolor='white')
print("Saved plot to tools/angular_tuning_output.png")